[package]
name = "renorm"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
license-file = "LICENSE.txt"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0.148", features = ["derive"] }
